config/routes.rb
Trough::Engine.routes.draw do
  mount Refile.app, at: Refile.mount_point, as: :refile_app
  scope "/#{Trough.configuration.mount_path}" do
    resources :documents, path: "/", :except => :show, constraints: { id: /.*/ } do
      collection do
        get 'modal'
        get 'replace_modal'
        post 'modal_create'
        get 'search'
        get 'autocomplete'
      end
      member do
        get 'info', :constraints => { :id => /.*/ }
        patch 'replace', :constraints => { :id => /.*/ }
      end
      get 'links' => 'document_usages#links'
      get 'stats' => 'document_usages#stats'
    end

    get '/*id', to: 'documents#show', format: false
  end
end

app/models/trough/ability.rb
module Trough
  class Ability
    include CanCan::Ability

    def initialize(user)

      can [:show], Trough::Document

      return unless user
      if user.role.in?(%w( developer admin editor author ) << Trough.configuration.extra_roles)
        can :manage, Trough::Document
        can :manage, Trough::DocumentUsage
      end

      if user.role.in?(%w( author ))
        cannot :destroy, Trough::Document
      end
    end
  end
end

app/models/trough/document_usage.rb
module Trough
  class DocumentUsage < ActiveRecord::Base

    belongs_to :document, foreign_key: 'trough_document_id'
    validates :document, presence: true

    if GemHelper.gem_loaded? :pig
      belongs_to :content_package, class_name: '::Pig::ContentPackage', foreign_key: 'pig_content_package_id'
      belongs_to :unscoped_content_package, -> { unscope(where: :archived_at) }, class_name: '::Pig::ContentPackage', foreign_key: 'pig_content_package_id'
      validates :content_package, presence: { allow_nil: true }
      validates :document, uniqueness: { scope: :content_package, allow_nil: true }
    end

    def self.active
      where(active: true)
    end

    def activate!
      update_attribute(:active, true)
    end

    def deactivate!
      update_attribute(:active, false)
    end

    def unlink_content_package!
      update_attributes(active: false, pig_content_package_id: nil)
    end
  end
end

app/controllers/trough/application_controller.rb
module Trough
  class ApplicationController < ::Pig::Admin::ApplicationController
    before_action :merge_abilities

    protected

    # extend the existing abilities generated by pig
    def merge_abilities
      current_ability.merge(Trough::Ability.new(current_user))
    end
  end
end

app/controllers/trough/document_usages_controller.rb
module Trough
  class DocumentUsagesController < ApplicationController

    before_action :find_document

    layout false

    def links
      @document_usages = @document.document_usages.
        active.includes(:content_package)
    end

    def stats
      @document_usages = @document.document_usages.includes(:content_package)
    end

    private

      def find_document
        @document = Document.
          includes(:document_usages).find(params[:document_id])
        authorize! :edit, @document
      end

  end
end

app/controllers/trough/documents_controller.rb
module Trough
  class DocumentsController < ::Trough::ApplicationController

    load_and_authorize_resource
    skip_load_resource only: [:show, :destroy, :info, :replace]

    before_action :prepare_new_document, only: [:index, :search]

    helper_method :sort_column, :sort_direction

    def index
      docs = Document.include_meta.all
      @documents = docs.order("LOWER(NULLIF(#{sort_column}, '')) #{sort_direction}")
    end

    def search
      @documents = Document.include_meta.search(params[:term]).order(:slug)
      render :index
    end

    def autocomplete
      render json: Document.search(params[:term]).pluck(:slug).to_json
    end

    def new
    end

    def create
      @new_document = true
      @document.uploader = current_user.full_name if current_user && current_user.full_name

      return if @document.save
      @duplicate_document = Document.find_by(md5: @document.md5) if @document.errors[:md5]
    end

    def destroy
      @document = Document.find_by(slug: params[:id])
      @d_id = @document.attributes['id']
      @document.destroy
      flash[:notice] = "Document deleted."
      redirect_to documents_path
    end

    def edit
    end

    def update
    end

    def replace
      @document = Document.find_by(slug: params[:id])
      if @document.update(document_params.merge(description: @document.get_description_or_default))
        flash[:notice] = "#{@document.file_filename} replaced"
      elsif @document.errors[:md5]
        @duplicate_document = Document.find_by(md5: @document.md5)
      end
    end

    def info
      @document = Document.find_by(slug: params[:id])
      json = @document.as_json(include: { document_usages: { include: { unscoped_content_package: { only: [:name] } } } }, methods: :uploaded_on)
      json["share_url"] = trough.document_url(@document)
      render json: json.to_json
    end

    def show
      uri = URI(request.referer || "")
      # attempt to find document by slug without file extension, if unable to find with it
      @document = Document.find_by(slug: params[:id]) || Document.find_by(slug: params[:id].split('.')[0...-1].join('.'))
      if GemHelper.gem_loaded?(:pig)
        permalink = ::Pig::Permalink.find_from_url(uri.path)
        if permalink
          usage = DocumentUsage.where(document:@document, pig_content_package_id: permalink.resource_id).first
          usage.update_attribute(:download_count, usage.download_count + 1) if usage
        end
      end
      if @document
        redirect_to @document.s3_url
      else
        redirect_to pig.not_found_url
      end
    end

    def modal
      @documents = Document.all
      @document = Document.new
      render :layout => false
    end

    def replace_modal
      @document = Document.find(params[:id])
      render :layout => false
    end

    def modal_create
      @document = Document.new(document_params)
      @document.uploader = current_user.full_name if current_user && current_user.full_name
      if !@document.save && @document.errors[:md5]
        @duplicate_document = Document.find_by(md5: @document.md5)
      else
        @document = Document.include_meta.find(@document.id)
      end
    end

    private

    def document_params
      params.require(:document).permit(:file, :slug, :description)
    end

    def prepare_new_document
      @document = Document.new
    end

    def sort_column
      Document.column_names.include?(params[:sort]) ? params[:sort] : 'slug'
    end

    def sort_direction
      %w(asc desc).include?(params[:direction]) ? params[:direction] : 'asc'
    end
  end
end

app/helpers/trough/application_helper.rb
module Trough
  module ApplicationHelper
    
  # Gets page title - uses long_page_title if meta_title not set. If neither, or not a pig page, uses default.
  def get_meta_title

    meta_title = Settings.default_meta_title

    if @content_package.present?

      if @content_package.meta_title.present?
        meta_title = "#{@content_package.meta_title} | #{Settings.default_meta_title}"
      elsif @content_package.respond_to?(:long_page_title)
        meta_title = "#{@content_package.long_page_title} | #{Settings.default_meta_title}"
      end

    end

    meta_title

  end

  # Gets meta tags - uses pig values or default except for meta image
  # Uses the hero image if no meta image is set. If neither, or not a pig page, uses default
  def get_meta_tags
    if @content_package.present?

      if @content_package.meta_image_uid
        image = "http://#{Settings.site_url}#{@content_package.meta_image.thumb('1024x1024#').url}"
      elsif @content_package.respond_to?(:hero_image) && @content_package.hero_image.present?
        image = "http://#{Settings.site_url}#{@content_package.hero_image.thumb('1024x1024#').url}"
      end

      meta_title = @content_package.meta_title.presence || Settings.default_meta_title
      meta_description = @content_package.meta_description.presence || Settings.default_meta_description
      meta_keywords = @content_package.meta_keywords.presence || Settings.default_meta_keywords
      if @content_package.hide_from_robots?
        meta_hide_from_robots = "<meta name='robots' content='noindex, nofollow' />\n"
      end

    else
      meta_title = Settings.default_meta_title
      meta_description = Settings.default_meta_description
      meta_keywords = Settings.default_meta_keywords
      meta_hide_from_robots = nil

    end

    meta_image = image || "http://#{Settings.site_url}#{asset_path(Settings.default_fb_meta_image)}"

    meta_values = [meta_title, meta_description, meta_image, meta_keywords, meta_hide_from_robots]

    pig_meta_tags(meta_values)
  end

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current fa fa-sort-#{sort_direction}" : nil
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to sort: column, direction: direction do
      (title + content_tag(:i, "", class: css_class)).html_safe
    end
  end

  end
end

app/helpers/trough/layout_helper.rb
module Trough
  module LayoutHelper
    
    def body_tag(options = {}, &block)
      options[:id] ||= id_for_body_tag
      body_class = "#{classes_for_body_tag} #{options[:class]}".strip
      options[:class] = body_class unless body_class.blank?
      concat content_tag(:body, capture(&block), options)
    end

private
def id_for_body_tag
  is_home? ? 'home' : 'inside'
end

def is_home?
  @is_home || controller_name == "home"
end

def classes_for_body_tag
  [].tap do |classes|
    classes << "controller_#{controller_name}"
    classes << "action_#{action_name}"
    # classes << (current_user? ? 'logged_in' : 'logged_out')
    # classes << (current_user ? 'logged_in' : 'logged_out')
    # classes << (current_user ? "role-#{current_user.role}" : 'role-anonymous')
    classes << "root_slug_#{@page.root_slug}" if defined?(@page) && @page && @page.root && @page.root_slug.present?
    classes << "slug_#{@page.slug}" if defined?(@page) && @page && @page.slug.present?
  end.join(' ')
end

end
end

app/helpers/trough/meta_tags_helper.rb
module Trough
  module MetaTagsHelper

    def header_page_title
      meta_title, meta_description, meta_image, meta_keywords, meta_hide_from_robots = build_meta_values
      meta_title
    end

    # Takes an optional parameter of meta_values
    # If not provided meta_values are auto-generated where possible
    # Params:
    # meta_values  [meta_title, meta_description, meta_image, meta_keywords, meta_hide_from_robots]
    def pig_meta_tags(meta_values = nil)
      if meta_values.nil?
        meta_values = build_meta_values
      end
      meta_tags = build_meta_tags(meta_values)
      meta_tags.html_safe
    end

    # builds meta data needed for generating meta tags
    def build_meta_values
      page_slug = request.path.match(/^\/(.+)$/) { $1 }
      if @content_package.present?
        # cache content_package_meta_tags_cache_key(@content_package) do

        meta_title = @content_package.meta_title.presence || Settings.default_meta_title
        meta_description = @content_package.meta_description.presence || Settings.default_meta_description
        meta_image = @content_package.meta_image_uid ? "#{Settings.site_url}#{@content_package.meta_image.thumb('300x300#').url}" : "#{Settings.site_url}#{image_path(Settings.default_fb_meta_image)}"
        meta_keywords = @content_package.meta_keywords.presence || Settings.default_meta_keywords

        if @content_package.hide_from_robots?
          meta_hide_from_robots = "<meta name='robots' content='noindex, nofollow' />\n"
        end
        [meta_title, meta_description, meta_image, meta_keywords, meta_hide_from_robots]
        # end
      elsif meta_data = Pig::MetaDatum.where(page_slug: page_slug).first
        meta_title = meta_data.title || Settings.default_meta_title
        meta_description = meta_data.description || Settings.default_meta_description
        meta_image = meta_data.image_uid ? "#{Settings.site_url}#{meta_data.image.thumb('300x300#').url}" : "#{Settings.site_url}#{image_path(Settings.default_fb_meta_image)}"
        meta_keywords = meta_data.keywords || Settings.default_meta_keywords
        [meta_title, meta_description, meta_image, meta_keywords, nil]
      end
    end

    # generates meta tags from data
    def build_meta_tags(meta_values, include_keywords = true)
      meta_title, meta_description, meta_image, meta_keywords, meta_hide_from_robots = meta_values
      meta_tags = meta_hide_from_robots.to_s
      # build actual tags from values

      if meta_image.present?
        meta_tags << "<meta name=\"twitter:card\" content=\"photo\">\n"
      else
        meta_tags << "<meta name=\"twitter:card\" content=\"summary\">\n"
      end

      if meta_title.present?
        meta_tags << "<meta itemprop=\"name\" content=\"#{meta_title}\">\n"
        meta_tags << "<meta name=\"twitter:title\" content=\"#{meta_title}\">\n"
        meta_tags << "<meta property=\"og:title\" content=\"#{meta_title}\" />\n"
      end

      if meta_description.present?
        meta_tags << "<meta name=\"description\" content=\"#{meta_description}\">\n"
        meta_tags << "<meta itemprop=\"description\" content=\"#{meta_description}\">\n"
        meta_tags << "<meta name=\"twitter:description\" content=\"#{meta_description}\">\n"
        meta_tags << "<meta property=\"og:description\" content=\"#{meta_description}\" />\n"
      end

      if meta_image.present?
        meta_tags << "<meta itemprop=\"image\" content=\"#{meta_image}\">\n"
        meta_tags << "<meta property=\"og:image\" content=\"#{meta_image}\"/>\n"
      end

      if meta_keywords.present? && include_keywords
        meta_tags << "<meta name=\"keywords\" content=\"#{meta_keywords}\">\n"
      end

      meta_tags << "<meta property=\"og:url\" content=\"#{request.original_url}\" />\n"
      meta_tags << "<meta property=\"twitter:url\" content=\"#{request.original_url}\" />\n"
      meta_tags << "<meta property=\"og:site_name\" content=\"#{Settings.site_name}\"/>\n"

      meta_tags
    end

  end
end

app/helpers/trough/title_helper.rb
module Trough::TitleHelper
  
  def title(text)
    @page_title ||= text
  end
  
  def page_title
    [Settings.site_name, @page_title].compact.join(' - ')
  end
  
end

app/views/trough/documents/_document.html.haml
-doc_link = document_url(document)
%tr.document-row{ data: { document_info_modal: document.slug }}
  %td.documents-name-column
    =document.slug
  %td.documents-link-column
    =document.description.presence ? document.description.truncate(100) : ""
  %td.documents-uploader-column
    =document.uploader
  %td.documents-usage-column
    -if @new_document
      0
    - elsif document.active_document_usage_count > 0
      = document.active_document_usage_count
    - else
      = document.active_document_usage_count
  %td.documents-downloads-column
    -if @new_document
      0
    - elsif document.downloads_count
      = document.downloads_count
    - else
      0

app/views/trough/documents/_form.html.haml
=semantic_form_for @document || Trough::Document.new, url: documents_path, remote: true do |form|
  =hidden_field_tag "authenticity_token", form_authenticity_token
  =form.inputs do
    =form.attachment_field :file, presigned: true
    .progress
      .progress-bar{role: "progressbar", style: "width: 0%;"}
    =form.input :description, wrapper_html: { style: "display: #{@document && @document.errors.key?(:description) ? 'block' : 'none'}" }

  =form.actions do
    =form.action :submit, label: 'Upload file', button_html: { class: 'btn btn-primary pull-right', disabled: true }

app/views/trough/documents/_search.html.haml
= form_tag search_documents_path, method: :get,
  enforce_utf8: false,
  id: 'document-search' do
  %fieldset.inputs
    = text_field_tag :term, params[:term],
      data: {source: autocomplete_documents_path},
      autocomplete: 'off',
      placeholder: 'Quick find: Start typing the name of a document, the author or description'

app/views/trough/documents/create.js.erb
$('#document-form').html("<%= escape_javascript render 'form' %>");
<% if @document.errors.empty? %>
  $('.document-row:last').after("<%= escape_javascript render 'document', :document => @document %>");
  $(".js-file-uploaded").hide();
<% else %>
  <% if @duplicate_document.present? %>
    documentHelpers.showDuplicateDocumentAlert("<%= @duplicate_document.slug %>", function(slug){
      DocumentInfoModal.show(slug);
    });
  <% end %>
   $('#document_submit_action').removeAttr('disabled');
<% end %>

app/views/trough/documents/destroy.js.erb
var d_id = '<%= @d_id %>';
$('.document-row[data-document-id="' + d_id +'"]').remove();

app/views/trough/documents/index.html.haml
:javascript
  $(document).ready(function() {
    $('#alpha-filter').change(function() {
      var value = $(this).val();
      if (value == 'All')
      {
        $('.document-row').show();
      }
      else
      {
        $('.document-row').hide();
        $('.document-row[data-filter="'+ value +'"]').show();
      }
    });
  });

.container.cms-main#cms-style-container
  =render('pig/admin/content_packages/sitemap_header', header_title: 'Documents')
  .row
    .col-xs-12.documents
      #document-form.documents-form
        =render('form')
      = render('search')
      %table.cms-table
        %thead
          %tr
            %th.documents-name-column
              =sortable 'slug', 'Name'
            %th.documents-link-column
              =sortable 'description'
            %th.documents-usage-column
              =sortable 'uploader', 'Uploaded by'
            %th.documents-usage-column Used
            %th.documents-downloads-column Downloaded
        %tbody
          =render(@documents)

#usageLinks.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %a.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %i.fa.fa-times
        %h4.modal-title Document Usage
      .modal-body

#usageStats.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %h4.modal-title Document Downloads
      .modal-body
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

#documentReplace.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %a.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %i.fa.fa-times
        %h4.modal-title Replace Document
      .modal-body

app/views/trough/documents/modal.html.haml
.modal-header
  %a.close{"aria-label" => "Close", "data-dismiss" => "modal"}
    %i.fa.fa-times
  %h4.modal-title Documents
.modal-body.ui-front.document-modal
  %label.col-primary Choose an existing file
  =select_tag "document", options_for_select(@documents.collect{|doc| [doc.slug, {id: doc.id, url: document_path(doc), name: doc.file_filename}.to_json] }), class: "autocomplete-select"
  %label.col-primary Or upload a new file
  =form_for @document, url: modal_create_documents_path, id: 'new_document', remote: true  do |form|
    =form.attachment_field :file, presigned: true
    .progress
      .progress-bar{role: "progressbar", style: "width: 0%;"}
    %label.col-primary#document_description_label{style: 'display:none'} Description (mandatory)
    =form.text_area :description, style: 'display:none', id: "document_description_input"
    .modal-footer
      =form.submit "Upload file", id: 'document_submit_action', class: 'btn btn-primary', disabled: true

app/views/trough/documents/modal_create.js.erb
<% if @document.errors.empty? %>
  RemoteModal.completed({ id: <%= @document.id %>, url: "<%= Trough::Engine.routes.url_helpers.document_path(@document) %>", name: "<%= @document.file_filename %>" });
  $('.document-row:last').after("<%= escape_javascript render 'document', :document => @document %>");
<% else %>
  <% if @duplicate_document.present?  %>
    documentHelpers.showDuplicateDocumentAlert("<%= @duplicate_document.slug %>", function(slug) {
      RemoteModal.completed({
        id: <%= @duplicate_document.id %>,
        name: "<%= @duplicate_document.slug %>",
        url: "/documents/<%= @duplicate_document.slug %>"
      })
    }, "Use this instead");
  <% end %>
<% end %>

app/views/trough/documents/replace.js.erb
<% if @document.errors.empty? %>
  DocumentReplaceModal.hide();
  location.reload();
<% else %>
  <% if @duplicate_document.present? %>
    documentHelpers.showDuplicateDocumentAlert("<%= @duplicate_document.slug %>", function(slug){
      DocumentReplaceModal.hide();
      DocumentInfoModal.show(slug);
    }, "Show", $("form#replace_document"));
  <% elsif @document.errors[:file_content_type].present? %>
    DocumentReplaceModal.showContentTypeWarning();
  <% end %>
<% end %>

app/views/trough/documents/replace_modal.html.haml
.modal-header
  %a.close{"aria-label" => "Close", "data-dismiss" => "modal"}
    %i.fa.fa-times
  %h4.modal-title Replace document
.modal-body.ui-front.document-modal
  %label.col-primary="Upload a new file to replace #{@document.file_filename}"
  =form_for @document, url: replace_document_path(@document), html: { id: 'replace_document' }, remote: true  do |form|
    =form.attachment_field :file, presigned: true
    .progress
      .progress-bar{role: "progressbar", style: "width: 0%;"}
    .modal-footer
      =form.submit "Replace", id: 'document_submit_action', class: 'btn btn-primary', disabled: true